package com.drools.example
rule "Hello World"
when
    helloWorldObject: HelloWorld()
then
    helloWorldObject.showMessage();
    System.out.println(" from Drools!");
end

rule "setup"
when
then
    insert(new Pomiar(200, 200));
    insert(new Pomiar(300, 300));
end

rule "dym"
when
    exists Pomiar(dym >0, temperatura >=150)
then
    insert(new Pozar());
end

rule "pozar"
when
    pozarObject : Pozar()
then
    System.out.println("Pali się!");
end

rule "pozar telefon"
when
    pozarObject : Pozar()
then
    insert(new Telefon("112") );
end

rule "wyswietl telefon"
when
    telefon: Telefon()
then
    System.out.println("Prosze zadzwonić na numer "+telefon.numer);
//    telefon.numer="998";
//    update(telefon);
end

rule "straz przyjazd"
when
    straz : Straz() and
    pozar : Pozar()
then
    System.out.println("Straz przyjechała!");
    retract(pozar);
end

rule "straz odjzad"
when
    not Pozar() and
    straz : Straz()
then
    System.out.println("Odjzaz strazy");
    retract(straz);
end